name: Publish Dev

on:
  workflow_dispatch:
  schedule: [cron: "0 0 * * 0"]

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install lib32z1 libc6-dev-i386 lib32z1-dev libbz2-1.0:i386 xserver-xorg-dev:i386 libfreetype6-dev:i386
        curl -sL 'https://github.com/wine-mirror/wine/archive/refs/heads/master.zip' -o wine.zip
        unzip -q wine.zip
        mkdir -p wine-master/build
        cd wine-master
        ./configure --prefix=$(pwd)/build
        make
        make install
        cp build/wine64 build/wine
        tar -czvf ../wine.tar.gz build/
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: wine.tar.gz
        asset_name: wine.tar.gz
        tag: "Wine-Dev"
        overwrite: true
        body: "## This Release Is Updated Every Week, Don't Worry If The Tag Is Old.\nPlease Don't Use This For Personal Use, [Build It Yourself](https://wiki.winehq.org/Building_Wine), Or [Download The Prebuild Binary](https://wiki.winehq.org/Download)."
